%YAML:1.0
---
baseDir: "/home/ajhalme/projects/humanpatterns-qt/"
patternDirectory: "/home/ajhalme/projects/humanpatterns-qt/patterns"
gamesDirectory: "/home/ajhalme/projects/humanpatterns-qt/games"    
blurValue: 8
threshValue: 20
gameMode: 0
advanceThreshold: 60
audioOn: 1
minPatternScore: 151
rotation: 0
